"""The canonical provider catalog. The agent treats this as the seed and
adds new providers discovered at runtime; never removes anything from here
without an explicit decision recorded in the changelog."""
from .models import Provider, Model, CreditProvider

# Canonical public sites, pinned where host-derivation would land on an
# API subdomain or a different brand domain. Anything not listed here is
# derived from the api_base host at run time.
HOMEPAGES: dict[str, str] = {
    "p_zai": "https://z.ai",
    "p_chutes": "https://chutes.ai",
    "p_groq": "https://groq.com",
    "p_google": "https://aistudio.google.com",
    "p_cerebras": "https://www.cerebras.ai",
    "p_mistral": "https://mistral.ai",
    "p_cohere": "https://cohere.com",
    "p_together": "https://www.together.ai",
    "p_fireworks": "https://fireworks.ai",
    "p_deepinfra": "https://deepinfra.com",
    "p_sambanova": "https://sambanova.ai",
    "p_nvidia": "https://www.nvidia.com/en-us/ai-data-science/",
    "p_cloudflare": "https://developers.cloudflare.com/workers-ai/",
    "p_github": "https://github.com/marketplace/models",
    "p_hf": "https://huggingface.co/docs/inference-providers",
    "p_openrouter": "https://openrouter.ai",
    "p_qwen": "https://www.alibabacloud.com/en/product/modelstudio",
    "p_moonshot": "https://www.moonshot.ai",
    "p_deepseek": "https://www.deepseek.com",
    "p_siliconflow": "https://siliconflow.cn",
    "p_zuki": "https://zuki.ai",
    "p_naga": "https://naga.ac",
    "p_anannas": "https://anannas.ai",
    "p_novita": "https://novita.ai",
    "p_nscale": "https://nscale.com",
    "p_publicai": "https://publicai.co",
    "p_glhf": "https://glhf.chat",
    "p_bai": "https://b.ai",
    "p_targon": "https://targon.com",
    "p_xkiro": "https://xkiro.com",
    "p_experiential": "https://platform.experientiallabs.ai",
    "p_tokenrouter": "https://www.tokenrouter.com",
    "p_tabitoken": "https://tabitoken.com",
    "p_hcnsec": "https://api.hcnsec.cn",
    "p_api": "https://voidai.app",
    "p_api_2": "https://naga.ac",
    "p_helixmind": "https://helixmind.online",
    "p_api_3": "https://api.navy",
    "p_api_4": "https://mnnai.ru",
    "p_hcap": "https://hcap.ai",
}

PROVIDERS: list[Provider] = [
    Provider(id="p_zai", slug="zai", name="Z.ai (Zhipu / BigModel)", region="China",
             api_base="https://api.z.ai/api/paas/v4", openai_compatible=True, api_key_env="ZAI_API_KEY",
             tagline="GLM-4 family with a generous free tier.",
             notes="Often missed by Western dashboards. Best read of the user's 'b.ai'."),
    Provider(id="p_chutes", slug="chutes", name="Chutes.ai", region="Global",
             api_base="https://llm.chutes.ai/v1", openai_compatible=True, api_key_env="CHUTES_API_KEY",
             tagline="Serverless inference with promo credits."),
    Provider(id="p_groq", slug="groq", name="Groq", region="US",
             api_base="https://api.groq.com/openai/v1", openai_compatible=True, api_key_env="GROQ_API_KEY"),
    Provider(id="p_google", slug="google-ai-studio", name="Google AI Studio (Gemini)", region="Global",
             api_base="https://generativelanguage.googleapis.com/v1beta", openai_compatible=True, api_key_env="GOOGLE_API_KEY",
             modalities=["chat", "embedding", "image", "audio_tts", "video", "vision"]),
    Provider(id="p_cerebras", slug="cerebras", name="Cerebras", region="US",
             api_base="https://api.cerebras.ai/v1", openai_compatible=True, api_key_env="CEREBRAS_API_KEY"),
    Provider(id="p_mistral", slug="mistral", name="Mistral (La Plateforme)", region="EU",
             api_base="https://api.mistral.ai/v1", openai_compatible=True, api_key_env="MISTRAL_API_KEY",
             modalities=["chat", "embedding", "ocr"]),
    Provider(id="p_cohere", slug="cohere", name="Cohere", region="US",
             api_base="https://api.cohere.com/v1", openai_compatible=False, api_key_env="COHERE_API_KEY",
             signup_friction="trial_card",
             modalities=["chat", "embedding", "rerank"]),
    Provider(id="p_together", slug="together", name="Together AI", region="US",
             api_base="https://api.together.xyz/v1", openai_compatible=True, api_key_env="TOGETHER_API_KEY"),
    Provider(id="p_fireworks", slug="fireworks", name="Fireworks AI", region="US",
             api_base="https://api.fireworks.ai/inference/v1", openai_compatible=True, api_key_env="FIREWORKS_API_KEY"),
    Provider(id="p_deepinfra", slug="deepinfra", name="DeepInfra", region="US",
             api_base="https://api.deepinfra.com/v1/openai", openai_compatible=True, api_key_env="DEEPINFRA_API_KEY"),
    Provider(id="p_sambanova", slug="sambanova", name="SambaNova", region="US",
             api_base="https://api.sambanova.ai/v1", openai_compatible=True, api_key_env="SAMBANOVA_API_KEY"),
    Provider(id="p_nvidia", slug="nvidia-nim", name="NVIDIA NIM", region="US",
             api_base="https://integrate.api.nvidia.com/v1", openai_compatible=True, api_key_env="NVIDIA_API_KEY",
             modalities=["chat", "embedding", "image", "vision"]),
    Provider(id="p_cloudflare", slug="cloudflare", name="Cloudflare Workers AI", region="Global",
             api_base="https://api.cloudflare.com/client/v4/accounts/{account_id}/ai/v1", openai_compatible=True, api_key_env="CLOUDFLARE_API_TOKEN",
             modalities=["chat", "embedding", "image", "audio_tts", "audio_stt"]),
    Provider(id="p_github", slug="github-models", name="GitHub Models", region="Global",
             api_base="https://models.inference.ai.azure.com", openai_compatible=True, api_key_env="GITHUB_TOKEN",
             signup_friction="github"),
    Provider(id="p_hf", slug="huggingface", name="Hugging Face Inference Providers", region="Global",
             api_base="https://router.huggingface.co/v1", openai_compatible=True, api_key_env="HF_TOKEN",
             modalities=["chat", "embedding", "image", "audio_stt"]),
    Provider(id="p_openrouter", slug="openrouter", name="OpenRouter (free variants)", region="Global",
             api_base="https://openrouter.ai/api/v1", openai_compatible=True, api_key_env="OPENROUTER_API_KEY"),
    Provider(id="p_qwen", slug="qwen-bailian", name="Alibaba Bailian (Qwen)", region="China",
             api_base="https://dashscope.aliyuncs.com/compatible-mode/v1", openai_compatible=True, api_key_env="DASHSCOPE_API_KEY",
             signup_friction="phone"),
    Provider(id="p_moonshot", slug="moonshot", name="Moonshot AI (Kimi)", region="China",
             api_base="https://api.moonshot.cn/v1", openai_compatible=True, api_key_env="MOONSHOT_API_KEY",
             signup_friction="phone"),
    Provider(id="p_deepseek", slug="deepseek", name="DeepSeek", region="China",
             api_base="https://api.deepseek.com/v1", openai_compatible=True, api_key_env="DEEPSEEK_API_KEY",
             signup_friction="phone"),
    Provider(id="p_siliconflow", slug="siliconflow", name="SiliconFlow", region="China",
             api_base="https://api.siliconflow.cn/v1", openai_compatible=True, api_key_env="SILICONFLOW_API_KEY",
             signup_friction="phone"),
    Provider(id="p_zuki", slug="zuki", name="Zuki", region="Global",
             api_base="https://api.zuki.ai/v1", openai_compatible=True, api_key_env="ZUKI_API_KEY"),
    Provider(id="p_naga", slug="nagaai", name="NagaAI", region="Global",
             api_base="https://api.nagaai.org/v1", openai_compatible=True, api_key_env="NAGA_API_KEY"),
    Provider(id="p_anannas", slug="anannas", name="Anannas", region="Global",
             api_base="https://api.anannas.ai/v1", openai_compatible=True, api_key_env="ANANNAS_API_KEY"),
    Provider(id="p_novita", slug="novita", name="Novita", region="Global",
             api_base="https://api.novita.ai/v3/openai", openai_compatible=True, api_key_env="NOVITA_API_KEY"),
    Provider(id="p_nscale", slug="nscale", name="Nscale", region="EU",
             api_base="https://api.nscale.com/v1", openai_compatible=True, api_key_env="NSCALE_API_KEY"),
    Provider(id="p_publicai", slug="publicai", name="Public AI", region="US",
             api_base="https://api.publicai.co/v1", openai_compatible=True, api_key_env="PUBLICAI_API_KEY"),
    Provider(id="p_glhf", slug="glhf", name="GLHF", region="Global",
             api_base="https://api.glhf.chat/v1", openai_compatible=True, api_key_env="GLHF_API_KEY"),
    Provider(id="p_bai", slug="bai", name="b.ai", region="Global",
             api_base="https://api.b.ai/v1", openai_compatible=True, api_key_env="BAI_API_KEY",
             tagline="Multi-model API with a free tier. Resolves to whatever model you ask for.",
             notes="Surfaced via https://chat.b.ai/key. /v1/models is gated (401 without a key) but the chat surface advertises a free tier."),
    Provider(id="p_targon", slug="targon", name="Targon", region="US",
             api_base="https://api.targon.com/v1", openai_compatible=True, api_key_env="TARGON_API_KEY"),
    Provider(id="p_xkiro", slug="xkiro", name="Xkiro", region="Global",
             api_base="https://xkiro.com/v1", openai_compatible=True, api_key_env="XKIRO_API_KEY",
             tagline="Multi-model gateway with 40 zero-priced models. /v1/models is public and self-labels each row's access tier.",
             notes="Free classification is source-declared: access_tier=free or pricing 0/0 in the live listing."),
    Provider(id="p_experiential", slug="experiential-labs", name="Experiential Labs", region="Global",
             api_base="https://api.experientiallabs.ai/v1", openai_compatible=True,
             api_key_env="EXPERIENTIAL_LABS_API_KEY",
             tagline="LLM gateway with a free tier. Model list is gated behind platform login (Google OAuth) — needs a gateway virtual key.",
             notes="https://platform.experientiallabs.ai issues keys after OAuth sign-in; /v1/models returns 401 without one."),
    Provider(id="p_tokenrouter", slug="tokenrouter", name="TokenRouter", region="Global",
             api_base="https://api.tokenrouter.com/v1", openai_compatible=True,
             api_key_env="TOKENROUTER_API_KEY",
             tagline="Multi-model gateway advertising free models. /v1/models is gated behind an API key.",
             notes="https://www.tokenrouter.com/models lists the catalog; api.tokenrouter.com answers 401 without a key."),
    Provider(id="p_tabitoken", slug="tabitoken", name="TabiToken", region="Global",
             api_base="https://tabitoken.com/v1", openai_compatible=True,
             api_key_env="TABITOKEN_API_KEY",
             tagline="LLM gateway with free models. /v1/models is gated behind an API key.",
             notes="https://tabitoken.com/models lists the catalog; the API answers 401 without a key."),
    Provider(id="p_hcnsec", slug="hcnsec", name="Hcnsec", region="China",
             api_base="https://api.hcnsec.cn/v1", openai_compatible=True,
             api_key_env="HCNSEC_API_KEY",
             tagline="New API (one-api fork) gateway serving free-credit models; also registered as an OpenRadar verifier provider.",
             notes="api.hcnsec.cn runs a New API gateway: unauthenticated /v1/models answers "
                   "{\"error\": {\"type\": \"new_api_error\", \"message\": \"Invalid token\"}} — the list is "
                   "token-gated, not empty. Set HCNSEC_API_KEY to verify."),
]

# Pin canonical homepages after the list is built.
for _p in PROVIDERS:
    _p.homepage = HOMEPAGES.get(_p.id, "")


# Credit-based providers: offer free credits/money on signup, not free inference.
# These are separate from the main provider list because they don't provide
# permanently free API access — they give a one-time credit balance.
CREDIT_PROVIDERS: list[CreditProvider] = [
    CreditProvider(
        provider_id="p_tabitoken",
        name="TabiToken",
        signup_bonus_usd=None,
        credit_expiry_days=None,
        models_available=["See tabitoken.com/models (list is public; the API is key-gated)"],
        signup_friction="email",
        homepage="https://tabitoken.com",
        notes="Gateway advertising free models and signup credit promos. The credit amount "
              "varies and isn't published on a stable page — check the site for the current offer.",
    ),
    CreditProvider(
        provider_id="p_hcnsec",
        name="Hcnsec",
        signup_bonus_usd=None,
        credit_expiry_days=None,
        models_available=["MiniMax-M3", "see console for the full list"],
        signup_friction="email",
        homepage="https://api.hcnsec.cn",
        notes="New API (one-api fork) gateway with signup credit promos — amount varies, check the "
              "console. Also registered as an OpenRadar verifier provider; /v1/models is token-gated.",
    ),
    CreditProvider(
        provider_id="p_together",
        name="Together AI",
        signup_bonus_usd=5.0,
        credit_expiry_days=30,
        models_available=["All Together-hosted models (Llama, Mixtral, Qwen, etc.)"],
        signup_friction="email",
        homepage="https://www.together.ai",
        notes="$5 free credits on signup, expires in 30 days. No credit card required.",
    ),
    CreditProvider(
        provider_id="p_fireworks",
        name="Fireworks AI",
        signup_bonus_usd=1.0,
        credit_expiry_days=30,
        models_available=["All Fireworks-hosted models (Llama, Mixtral, Qwen, etc.)"],
        signup_friction="email",
        homepage="https://fireworks.ai",
        notes="$1 free credits on signup, expires in 30 days.",
    ),
    CreditProvider(
        provider_id="p_replicate",
        name="Replicate",
        signup_bonus_usd=10.0,
        credit_expiry_days=None,
        models_available=["All models on Replicate (Llama, SDXL, Whisper, etc.)"],
        signup_friction="github",
        homepage="https://replicate.com",
        notes="$10 free credits on signup (GitHub auth). Credits don't expire. Pay-as-you-go after.",
    ),
    CreditProvider(
        provider_id="p_anyscale",
        name="Anyscale Endpoints",
        signup_bonus_usd=5.0,
        credit_expiry_days=30,
        models_available=["Llama, Mistral, CodeLlama, and other open models"],
        signup_friction="email",
        homepage="https://www.anyscale.com/endpoints",
        notes="$5 free credits on signup, expires in 30 days.",
    ),
    CreditProvider(
        provider_id="p_lambda",
        name="Lambda Labs",
        signup_bonus_usd=10.0,
        credit_expiry_days=30,
        models_available=["Llama, Mistral, and other open models via Lambda Inference API"],
        signup_friction="email",
        homepage="https://lambdalabs.com",
        notes="$10 free credits on signup, expires in 30 days. Also offers GPU cloud.",
    ),
    CreditProvider(
        provider_id="p_runpod",
        name="RunPod",
        signup_bonus_usd=5.0,
        credit_expiry_days=30,
        models_available=["Serverless endpoints for any containerized model"],
        signup_friction="email",
        homepage="https://www.runpod.io",
        notes="$5-10 free credits on signup (varies by promotion), expires in 30 days. Serverless + pod GPU rental.",
    ),
    CreditProvider(
        provider_id="p_modal",
        name="Modal",
        signup_bonus_usd=30.0,
        credit_expiry_days=30,
        models_available=["Serverless functions for any model (bring your own container)"],
        signup_friction="email",
        homepage="https://modal.com",
        notes="$30/month free tier (renews monthly). Not a one-time credit — recurring monthly allowance.",
    ),
    CreditProvider(
        provider_id="p_hf",
        name="Hugging Face",
        signup_bonus_usd=10.0,
        credit_expiry_days=None,
        models_available=["Inference Endpoints, Inference Providers, Spaces GPU"],
        signup_friction="email",
        homepage="https://huggingface.co",
        notes="Free tier: 30k tokens/mo on Inference Providers + $10 credits for Inference Endpoints. Community free tier for HF-hosted models.",
    ),
    CreditProvider(
        provider_id="p_openrouter",
        name="OpenRouter",
        signup_bonus_usd=5.0,
        credit_expiry_days=None,
        models_available=["All models on OpenRouter (400+ models via unified API)"],
        signup_friction="email",
        homepage="https://openrouter.ai",
        notes="$1-5 free credits on signup (varies by promotion). Credits don't expire. Access to 50+ free models (:free variants) permanently.",
    ),
]
